version: '3.8'
services:
  omcp-r-sandbox:
    build: .
    environment:
      - SANDBOX_TIMEOUT=300
      - MAX_SANDBOXES=10
      - DOCKER_IMAGE=rocker/r-ver:latest
      - LOG_LEVEL=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    restart: unless-stopped
