version: '3'

services:
  mcp-python-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - node_modules:/app/node_modules

volumes:
  node_modules:
