[project]
name = "pysandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.0",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
]

[project.scripts]
pysandbox = "pysandbox:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
